In [59]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

In [60]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [61]:
data.shape

(10000, 14)

In [62]:
data.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [63]:
data.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [64]:
x=data.iloc[:,3:-1].values.reshape(-1,10)
y=data.iloc[:,-1].values.reshape(-1,1)

In [65]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x=ct.fit_transform(x)

In [81]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
x[:,4]=lb.fit_transform(x[:,4])
print(x[0:,:])

[[1.0 0.0 0 ... 1 1 101348.88]
 [0.0 0.0 1 ... 0 1 112542.58]
 [1.0 0.0 0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0 ... 0 1 42085.58]
 [0.0 1.0 0 ... 1 0 92888.52]
 [1.0 0.0 0 ... 1 0 38190.78]]


In [82]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [83]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [84]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model=Sequential()
model.add(Dense(units=4,activation='relu'))
model.add(Dense(units=1,activation='sigmoid'))

In [87]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [91]:
model.fit(x_train,y_train,batch_size=50,epochs=50)

Epoch 1/50
8000/8000 [==============================] - 0s 43us/sample - loss: 0.3375 - acc: 0.8624
Epoch 2/50
8000/8000 [==============================] - 0s 39us/sample - loss: 0.3375 - acc: 0.8614
Epoch 3/50
8000/8000 [==============================] - 0s 41us/sample - loss: 0.3374 - acc: 0.8621
Epoch 4/50
8000/8000 [==============================] - 0s 42us/sample - loss: 0.3374 - acc: 0.8612
Epoch 5/50
8000/8000 [==============================] - 0s 42us/sample - loss: 0.3374 - acc: 0.8633
Epoch 6/50
8000/8000 [==============================] - 0s 40us/sample - loss: 0.3372 - acc: 0.8627
Epoch 7/50
8000/8000 [==============================] - 0s 41us/sample - loss: 0.3372 - acc: 0.8620
Epoch 8/50
8000/8000 [==============================] - 0s 41us/sample - loss: 0.3371 - acc: 0.8619
Epoch 9/50
8000/8000 [==============================] - 0s 42us/sample - loss: 0.3372 - acc: 0.8634
Epoch 10/50
8000/8000 [==============================] - 0s 43us/sample - loss: 0.3372 - acc: 0.8627

In [105]:
y_pred=model.predict(x_test)
y_pred=y_pred>0.5
print(np.concatenate((y_pred.reshape(-1,1),y_test),axis=1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [106]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[1529,   66],
       [ 202,  203]])

In [107]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.866